name: Run Selenium Tests - On Push and PR closed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome (Specific Version 129)
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo apt-get install -y google-chrome-stable

    - name: Download ChromeDriver (Specific Version 129)
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/129.0.6668.100/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver-linux64.zip

    - name: Install Node.js and npm
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm

    - name: Check Node.js and npm version
      run: |
        node -v
        npm -v

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run Selenium tests
      run: node tests/testHomepageValidations.js

    - name: Create error screenshots directory if it doesn't exist
      run: mkdir -p ./error-screenshots

    - name: Upload Test Artifacts (screenshots, logs)
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: ./error-screenshots
