name: Run Selenium Tests - On Push and PR closed

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        sudo apt-get install -y libappindicator3-1 fonts-liberation

    - name: Get Chrome version and install compatible ChromeDriver
      run: |
        # Get Chrome version (output is like "Google Chrome 129.x.x.x")
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
        echo "Chrome version is: $CHROME_VERSION"

        # Download the appropriate version of ChromeDriver
        LATEST_DRIVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        echo "Latest compatible ChromeDriver version is: $LATEST_DRIVER"

        # Download and install ChromeDriver
        wget "https://chromedriver.storage.googleapis.com/$LATEST_DRIVER/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install Node.js and npm
      run: |
        sudo apt-get install -y nodejs npm

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: node tests/testHomepageValidations.js

    - name: Upload Test Artifacts (screenshots, logs)
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: ./error-screenshots
