name: Run Selenium Tests - On Push and PR closed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        sudo apt-get install -y libappindicator3-1 fonts-liberation

    - name: Get the Latest ChromeDriver version
      id: get_chromedriver_version
      run: |
        LATEST_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Install ChromeDriver (Latest Version)
      run: |
        wget https://chromedriver.storage.googleapis.com/${{ env.LATEST_VERSION }}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Install Node.js and npm (via NodeSource for latest versions)
      run: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo apt-get install -y npm

    - name: Install dependencies
      run: npm install

    - name: Run Selenium tests
      run: node tests/testHomepageValidations.js

    - name: Create error screenshots directory if it doesn't exist
      run: mkdir -p ./error-screenshots

    - name: Upload Test Artifacts (screenshots, logs)
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: ./error-screenshots
